# Generated by Django 3.0.3 on 2020-03-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('agree_location', models.NullBooleanField()),
                ('agree_promotion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.URLField(blank=True, max_length=500, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('refund_account', models.IntegerField(blank=True, null=True)),
                ('refund_bank', models.CharField(blank=True, max_length=45, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=45, null=True)),
                ('facebook_id', models.CharField(max_length=45, null=True)),
                ('naver_id', models.CharField(max_length=45, null=True)),
                ('kakao_id', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
