# Generated by Django 3.0.3 on 2020-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200305_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='social_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
