# Generated by Django 3.0.3 on 2020-03-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200228_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='account',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='kakao_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='naver_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='account',
            name='refund_account',
        ),
        migrations.RemoveField(
            model_name='account',
            name='refund_bank',
        ),
    ]
