# Generated by Django 3.0.3 on 2020-03-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200301_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='agree_location',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='account',
            name='agree_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='facebook_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='kakao_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='naver_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='refund_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='refund_bank',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
