# Generated by Django 3.0.3 on 2020-03-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200305_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='MarketAgree',
            new_name='market_agree',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='RefundAccount',
            new_name='refund_account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='SnsConnection',
            new_name='sns_connection',
        ),
    ]
