# Generated by Django 3.0.3 on 2020-03-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200305_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='market_agree',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.MarketingAgree'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(blank=True, default=31874599, null=True),
        ),
    ]
