# Generated by Django 3.0.3 on 2020-03-02 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200302_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'social_platform',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='kakao_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='naver_id',
        ),
        migrations.AddField(
            model_name='account',
            name='sns_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='social_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SocialLog'),
        ),
    ]
