# Generated by Django 3.0.3 on 2020-03-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200307_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='market_agree',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.MarketingAgree'),
        ),
    ]
