# Generated by Django 3.0.3 on 2020-03-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'age',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Age')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='TravelObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_object', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'travel_objects',
            },
        ),
        migrations.CreateModel(
            name='ReviewTourProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.Review')),
                ('tour_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.TourProduct')),
            ],
            options={
                'db_table': 'review_tourproduct',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='tour_product',
            field=models.ManyToManyField(null=True, through='review.ReviewTourProduct', to='product.TourProduct'),
        ),
        migrations.AddField(
            model_name='review',
            name='travel_objet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.TravelObject'),
        ),
    ]
